export const createFamily = ({
  id,
  nome,
  cpf,
  telefone,
  logradouro,
  numero,
  endereco,
  bairro,
  status = "ativo",
  lastWithdrawalAt = null,
  createdById = null,
  createdByName = "Sistema",
  createdAt = null,
}) => ({
  id,
  nome,
  cpf,
  telefone,
  logradouro: logradouro || "",
  numero: numero || "",
  endereco: endereco || (logradouro ? `${logradouro}, ${numero || ""}`.trim() : ""),
  bairro,
  status,
  lastWithdrawalAt,
  createdById,
  createdByName,
  createdAt,
});
